

services:
  app:
    build:
      context: .
      args:
        - VITE_API_URL=/api
    container_name: darin-app
    restart: always
    ports:
      - "3001:3001"
      - "3005:3005"
    volumes:
      - ./database.sqlite:/app/server/database.sqlite
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_PATH=/app/server/database.sqlite
      - JWT_SECRET=your_secret_here
      - FRONTEND_URL=*
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# تم استخدام الملف المباشر لضمان عدم ضياع البيانات
