const AUDIT_ACTIONS = {
  // Authentication
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  TOKEN_VERIFIED: 'TOKEN_VERIFIED',

  // Password Reset
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  // Admins / Users
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',

  // Teachers
  TEACHER_CREATED: 'TEACHER_CREATED',
  TEACHER_UPDATED: 'TEACHER_UPDATED',
  TEACHER_DELETED: 'TEACHER_DELETED',
  TEACHER_SUSPENDED: 'TEACHER_SUSPENDED',

  // Students
  STUDENT_CREATED: 'STUDENT_CREATED',
  STUDENT_UPDATED: 'STUDENT_UPDATED',
  STUDENT_DELETED: 'STUDENT_DELETED',

  // Parents
  PARENT_CREATED: 'PARENT_CREATED',
  PARENT_UPDATED: 'PARENT_UPDATED',
  PARENT_DELETED: 'PARENT_DELETED',

  // Finance
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  INVOICE_PAID: 'INVOICE_PAID',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_DELETED: 'TRANSACTION_DELETED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  EXPORT_DATA: 'EXPORT_DATA',

  // Sessions
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_UPDATED: 'SESSION_UPDATED',
  SESSION_DELETED: 'SESSION_DELETED',

  // System
  SETTING_UPDATED: 'SETTING_UPDATED',
  BACKUP_CREATED: 'BACKUP_CREATED',
  SYSTEM_ERROR: 'SYSTEM_ERROR',

  // Account Migration (Sprint 2.2)
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_LINKED: 'ACCOUNT_LINKED',
  ACCOUNT_CUTOVER: 'ACCOUNT_CUTOVER',
  ACCOUNT_SKIPPED_DUPLICATE: 'ACCOUNT_SKIPPED_DUPLICATE',
  ACCOUNT_MIGRATION_FAILED: 'ACCOUNT_MIGRATION_FAILED',
  AUTH_SOURCE_ACCOUNTS: 'AUTH_SOURCE_ACCOUNTS',
  AUTH_SOURCE_LEGACY: 'AUTH_SOURCE_LEGACY',
};

const VALID_ACTIONS = new Set(Object.values(AUDIT_ACTIONS));

function isValidAction(action) {
  return VALID_ACTIONS.has(action);
}

module.exports = { AUDIT_ACTIONS, VALID_ACTIONS, isValidAction };
